### ISSUE TITLE
NotImplementedError: Wrong number or type of arguments for overloaded function '_vertcat'.

### ISSUE THREAD

**Issue by brunomorampc** [Eric-Bradford/UKF-SNMPC#1]
Hey Eric,

do you remember which version of casadi you used? I tried to run the example but I get this error

```
C:\Users\morabito\Documents\Repos\UKF-SNMPC\venv\lib\site-packages\casadi\casadi.py:168: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  if m.dtype!=np.object: return None
Traceback (most recent call last):
  File "C:\Users\morabito\Documents\Repos\UKF-SNMPC\Simulation_UKF_SNMPC.py", line 6, in <module>
    UKF_SNMPC                = UKF_SNMPC()
  File "C:\Users\morabito\Documents\Repos\UKF-SNMPC\UKF_SNMPC.py", line 42, in __init__
    self.set_inequality_constraints_UKF()
  File "C:\Users\morabito\Documents\Repos\UKF-SNMPC\UKF_SNMPC.py", line 483, in set_inequality_constraints_UKF
    Sigmapoints_a[k] = Sigma_points(x_hat[k-1],Sigma_chol[k-1],nun,sqrt_CovP,MeanP,nd,lambda_ukf,n_L) 
  File "C:\Users\morabito\Documents\Repos\UKF-SNMPC\UKF_SNMPC.py", line 393, in Sigma_points
    x_hat_a_previous = vertcat(x_hat_before,MeanP)
  File "C:\Users\morabito\Documents\Repos\UKF-SNMPC\venv\lib\site-packages\casadi\casadi.py", line 466, in vertcat
    def vertcat(*args): return _vertcat(args)
  File "C:\Users\morabito\Documents\Repos\UKF-SNMPC\venv\lib\site-packages\casadi\casadi.py", line 20204, in _vertcat
    return _casadi._vertcat(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function '_vertcat'.
  Possible prototypes are:
    _vertcat([Sparsity])
    _vertcat([DM])
    _vertcat([SX])
    _vertcat([MX])
  You have: '((np.array(SX),np.array(float)))'
```

It's due to the fact that you vertcat a SX variable with a numpy array. Maybe in older versions of casadi it was possible?

**Comment by Eric-Bradford** [comment]
Hi Bruno,

hope you are doing well :). To be honest I have no clue, but I fixed the issue. It should now run again with the newest Casadi version. 

It seems before I was vercat a SX variable with a numpy array filled with SX variables, which apparently it used to treat as a SX variable.
